# Generated by Django 4.2.23 on 2025-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_paid_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='base_price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Default base price (in cents)'),
        ),
        migrations.AddField(
            model_name='category',
            name='urgent_surcharge_percent',
            field=models.PositiveIntegerField(default=0, help_text='Urgent surcharge percentage'),
        ),
    ]
