# Generated by Django 4.2.23 on 2025-08-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_category_base_price_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Bootstrap Icons class, e.g. 'bi-scissors' or 'bi-suit'", max_length=100),
        ),
    ]
